### ISSUE TITLE
주제를 선정해봅시다.

### ISSUE THREAD

**Issue by SoeunShin** [SoeunShin/oss_team#1]
주제에 대해 의논해봐요!

**Comment by greenyeast** [comment]
스터디카페 자리 배정을 CRUD기능으로 구현?!

**Comment by SoeunShin** [comment]
오 좋은 것 같아요!

**Comment by SoeunShin** [comment]
구조체에 들어갈 항목들이 뭐가 있을까요?
ex)
사용자 이름
사용 시간 (입,퇴실 시간)
자리

**Comment by greenyeast** [comment]
혹시 다른 아이디어 없나요~! 없으시면 이 주제로 갈까요?

**Comment by SoeunShin** [comment]
자리 배정은 어떻게 구현할 수 있을까요??

**Comment by SoeunShin** [comment]
네 좋은 주제인 것 같아요~~ 이걸로 하죠!

**Comment by greenyeast** [comment]
예를들면 배열 하나 할당해서 이용자 자리배정이 되면 1로 표시하는 식으로 해서 하면 될것같아요!

**Comment by SoeunShin** [comment]
오 네!! 좋아요! 자리 개수는 30개 정도로 할까요?

**Comment by greenyeast** [comment]
네 좋아요!
