### ISSUE TITLE
함수에 대해 얘기해봐요!

### ISSUE THREAD

**Issue by SoeunShin** [SoeunShin/oss_team#3]
어떤 함수가 필요할까요?

**Comment by SoeunShin** [comment]
함수 10개 이상 정의해야 하는데 어떤 함수를 구현할까요?

**Comment by SoeunShin** [comment]
일단 CRUD, 파일 읽기, 파일 저장, 검색 정도가 있을 것 같아요!

**Comment by SoeunShin** [comment]
검색에는 빈자리 검색 외에 뭐가 필요할까요?

**Comment by greenyeast** [comment]
-검색기능: 이용현황(사용자가 현재 자리를 이용중인지 아닌지에 따라 이용중이 아니라면 얼마나 자리를 사용했는지의 정보), 현재 빈자리 개수, 현재 빈자리 번호 등

**Comment by greenyeast** [comment]
-Create: 현재 사용자 등록, 자리 배열생성

**Comment by SoeunShin** [comment]
사용중인 자리 검색
빈 자리 검색

**Comment by SoeunShin** [comment]
> -Create: 현재 사용자 등록, 자리 배열생성
- Read: 현재 사용중인 자리 조회

**Comment by SoeunShin** [comment]
> > -Create: 현재 사용자 등록, 자리 배열생성
> 
> - Read: 현재 사용중인 자리 조회
- update: 목록에 저장된 정보를 수정 (ex. 시간/사용자/자리)
- delete: 목록에 저장된 정보를 삭제

**Comment by SoeunShin** [comment]
검색: 사용중인 자리 검색, 빈자리 검색, 사용자 검색

**Comment by greenyeast** [comment]
Create: 현재 사용자 등록, 자리 배열생성
Read: 현재 사용중인 자리 조회(사용중인 자리, 빈자리 모두 출력)
update: 목록에 저장된 정보를 수정 (ex. 시간/사용자/자리)
delete: 목록에 저장된 정보를 삭제
검색: 사용중인 자리 검색, 빈자리 검색, 사용자 검색, 잔여시간
파일읽기, 파일저장

**Comment by SoeunShin** [comment]
구조체에 들어갈 항목은
- 사용자 이름
- 입실 시간
- 퇴실 시간
- 자리 번호
